const PDFDocument = require('pdfkit');
const fs = require('fs');
const path = require('path');
const moment = require('moment-timezone');
const logger = require('../utils/logger');

class PDFReportService {
  constructor() {
    this.timezone = 'Asia/Kolkata';
    this.currency = 'INR';
    this.currencySymbol = '₹';
  }

  /**
   * Format currency in INR
   * @param {number} amount - Amount to format
   * @returns {string} Formatted currency string
   */
  formatCurrency(amount) {
    return `${this.currencySymbol}${amount.toLocaleString('en-IN', {
      minimumFractionDigits: 2,
      maximumFractionDigits: 2
    })}`;
  }

  /**
   * Format date/time in IST
   * @param {Date|string} date - Date to format
   * @param {string} format - Moment format string
   * @returns {string} Formatted date string
   */
  formatDateTime(date, format = 'DD-MM-YYYY hh:mm A') {
    return moment(date).tz(this.timezone).format(format);
  }

  /**
   * Generate KPI report PDF
   * @param {Object} reportData - Report data containing KPIs
   * @param {string} outputPath - Path to save PDF
   * @returns {Promise<string>} Path to generated PDF
   */
  async generateKPIReport(reportData, outputPath) {
    try {
      logger.info(`Starting PDF generation for report: ${reportData.reportId || 'N/A'}`);

      // Ensure output directory exists
      const outputDir = path.dirname(outputPath);
      if (!fs.existsSync(outputDir)) {
        fs.mkdirSync(outputDir, { recursive: true });
      }

      return new Promise((resolve, reject) => {
        const doc = new PDFDocument({
          size: 'A4',
          margins: { top: 50, bottom: 50, left: 50, right: 50 }
        });

        const stream = fs.createWriteStream(outputPath);

        stream.on('finish', () => {
          logger.info(`PDF generated successfully: ${outputPath}`);
          resolve(outputPath);
        });

        stream.on('error', (error) => {
          logger.error(`PDF generation failed: ${error.message}`);
          reject(error);
        });

        doc.pipe(stream);

        // Header
        this._addHeader(doc, reportData);

        // Report metadata
        this._addMetadata(doc, reportData);

        // KPI Summary Section
        this._addKPISummary(doc, reportData.kpis || []);

        // Financial Metrics
        if (reportData.financialMetrics) {
          this._addFinancialMetrics(doc, reportData.financialMetrics);
        }

        // Performance Metrics
        if (reportData.performanceMetrics) {
          this._addPerformanceMetrics(doc, reportData.performanceMetrics);
        }

        // Employee Statistics
        if (reportData.employeeStats) {
          this._addEmployeeStats(doc, reportData.employeeStats);
        }

        // Customer Statistics
        if (reportData.customerStats) {
          this._addCustomerStats(doc, reportData.customerStats);
        }

        // Footer
        this._addFooter(doc, reportData);

        doc.end();
      });
    } catch (error) {
      logger.error(`Error in generateKPIReport: ${error.message}`, { stack: error.stack });
      throw error;
    }
  }

  /**
   * Add header to PDF
   * @private
   */
  _addHeader(doc, reportData) {
    doc
      .fontSize(24)
      .font('Helvetica-Bold')
      .text('KPI Dashboard Report', { align: 'center' })
      .moveDown();

    doc
      .fontSize(12)
      .font('Helvetica')
      .text(reportData.companyName || 'Dashboard Analytics', { align: 'center' })
      .moveDown(2);

    // Draw line
    doc
      .moveTo(50, doc.y)
      .lineTo(550, doc.y)
      .stroke();

    doc.moveDown();
  }

  /**
   * Add metadata section
   * @private
   */
  _addMetadata(doc, reportData) {
    const currentY = doc.y;

    doc.fontSize(10).font('Helvetica-Bold');
    doc.text('Report ID:', 50, currentY);
    doc.text('Generated On:', 50, currentY + 15);
    doc.text('Period:', 50, currentY + 30);
    doc.text('Generated By:', 50, currentY + 45);

    doc.font('Helvetica');
    doc.text(reportData.reportId || 'N/A', 150, currentY);
    doc.text(this.formatDateTime(new Date()), 150, currentY + 15);
    doc.text(
      `${this.formatDateTime(reportData.startDate, 'DD-MM-YYYY')} to ${this.formatDateTime(reportData.endDate, 'DD-MM-YYYY')}`,
      150,
      currentY + 30
    );
    doc.text(reportData.generatedBy || 'System', 150, currentY + 45);

    doc.moveDown(4);
  }

  /**
   * Add KPI summary section
   * @private
   */
  _addKPISummary(doc, kpis) {
    doc
      .fontSize(16)
      .font('Helvetica-Bold')
      .text('Key Performance Indicators', { underline: true })
      .moveDown();

    if (!kpis || kpis.length === 0) {
      doc.fontSize(10).font('Helvetica').text('No KPIs available').moveDown(2);
      return;
    }

    kpis.forEach((kpi, index) => {
      const startY = doc.y;

      // KPI Box
      doc
        .rect(50, startY, 495, 60)
        .fillAndStroke('#f0f0f0', '#cccccc');

      doc.fillColor('black');

      // KPI Name
      doc
        .fontSize(12)
        .font('Helvetica-Bold')
        .text(kpi.name, 60, startY + 10, { width: 200 });

      // KPI Value
      const value = kpi.isCurrency
        ? this.formatCurrency(kpi.value)
        : kpi.value.toLocaleString('en-IN');

      doc
        .fontSize(18)
        .font('Helvetica-Bold')
        .fillColor('#2c5aa0')
        .text(value, 280, startY + 15, { align: 'right', width: 250 });

      // Target and variance if available
      if (kpi.target !== undefined) {
        const variance = ((kpi.value - kpi.target) / kpi.target * 100).toFixed(2);
        const varianceColor = variance >= 0 ? '#28a745' : '#dc3545';
        
        doc
          .fontSize(9)
          .font('Helvetica')
          .fillColor('#666')
          .text(`Target: ${kpi.isCurrency ? this.formatCurrency(kpi.target) : kpi.target.toLocaleString('en-IN')}`, 60, startY + 35);

        doc
          .fillColor(varianceColor)
          .text(`${variance >= 0 ? '+' : ''}${variance}%`, 280, startY + 35, { align: 'right', width: 250 });
      }

      doc.fillColor('black');
      doc.moveDown(3);
    });

    doc.moveDown();
  }

  /**
   * Add financial metrics section
   * @private
   */
  _addFinancialMetrics(doc, metrics) {
    // Add new page if needed
    if (doc.y > 650) {
      doc.addPage();
    }

    doc
      .fontSize(16)
      .font('Helvetica-Bold')
      .text('Financial Metrics', { underline: true })
      .moveDown();

    doc.fontSize(10).font('Helvetica');

    const financialData = [
      ['Total Revenue', this.formatCurrency(metrics.totalRevenue || 0)],
      ['Total Expenses', this.formatCurrency(metrics.totalExpenses || 0)],
      ['Net Profit', this.formatCurrency(metrics.netProfit || 0)],
      ['Profit Margin', `${(metrics.profitMargin || 0).toFixed(2)}%`],
      ['Average Deal Value', this.formatCurrency(metrics.avgDealValue || 0)]
    ];

    financialData.forEach(([label, value]) => {
      doc.font('Helvetica-Bold').text(label, 60, doc.y);
      doc.font('Helvetica').text(value, 300, doc.y - 12, { align: 'right', width: 230 });
      doc.moveDown(0.5);
    });

    doc.moveDown(2);
  }

  /**
   * Add performance metrics section
   * @private
   */
  _addPerformanceMetrics(doc, metrics) {
    if (doc.y > 650) {
      doc.addPage();
    }

    doc
      .fontSize(16)
      .font('Helvetica-Bold')
      .text('Performance Metrics', { underline: true })
      .moveDown();

    doc.fontSize(10).font('Helvetica');

    const performanceData = [
      ['Tasks Completed', metrics.tasksCompleted || 0],
      ['Tasks Pending', metrics.tasksPending || 0],
      ['Completion Rate', `${(metrics.completionRate || 0).toFixed(2)}%`],
      ['Average Response Time', `${metrics.avgResponseTime || 0} hours`],
      ['Customer Satisfaction', `${(metrics.customerSatisfaction || 0).toFixed(1)}/5.0`]
    ];

    performanceData.forEach(([label, value]) => {
      doc.font('Helvetica-Bold').text(label, 60, doc.y);
      doc.font('Helvetica').text(value, 300, doc.y - 12, { align: 'right', width: 230 });
      doc.moveDown(0.5);
    });

    doc.moveDown(2);
  }

  /**
   * Add employee statistics
   * @private
   */
  _addEmployeeStats(doc, stats) {
    if (doc.y > 650) {
      doc.addPage();
    }

    doc
      .fontSize(16)
      .font('Helvetica-Bold')
      .text('Employee Statistics', { underline: true })
      .moveDown();

    doc.fontSize(10).font('Helvetica');

    const employeeData = [
      ['Total Employees', stats.totalEmployees || 0],
      ['Active Employees', stats.activeEmployees || 0],
      ['Average Productivity', `${(stats.avgProductivity || 0).toFixed(2)}%`],
      ['Department Count', stats.departmentCount || 0]
    ];

    employeeData.forEach(([label, value]) => {
      doc.font('Helvetica-Bold').text(label, 60, doc.y);
      doc.font('Helvetica').text(value, 300, doc.y - 12, { align: 'right', width: 230 });
      doc.moveDown(0.5);
    });

    doc.moveDown(2);
  }

  /**
   * Add customer statistics
   * @private
   */
  _addCustomerStats(doc, stats) {
    if (doc.y > 650) {
      doc.addPage();
    }

    doc
      .fontSize(16)
      .font('Helvetica-Bold')
      .text('Customer Statistics', { underline: true })
      .moveDown();

    doc.fontSize(10).font('Helvetica');

    const customerData = [
      ['Total Customers', stats.totalCustomers || 0],
      ['Active Customers', stats.activeCustomers || 0],
      ['New Customers (Period)', stats.newCustomers || 0],
      ['Customer Retention Rate', `${(stats.retentionRate || 0).toFixed(2)}%`],
      ['Average Customer Lifetime Value', this.formatCurrency(stats.avgLifetimeValue || 0)]
    ];

    customerData.forEach(([label, value]) => {
      doc.font('Helvetica-Bold').text(label, 60, doc.y);
      doc.font('Helvetica').text(value, 300, doc.y - 12, { align: 'right', width: 230 });
      doc.moveDown(0.5);
    });

    doc.moveDown(2);
  }

  /**
   * Add footer
   * @private
   */
  _addFooter(doc, reportData) {
    const pageCount = doc.bufferedPageRange().count;

    for (let i = 0; i < pageCount; i++) {
      doc.switchToPage(i);

      // Draw footer line
      doc
        .moveTo(50, 770)
        .lineTo(550, 770)
        .stroke();

      // Footer text
      doc
        .fontSize(8)
        .font('Helvetica')
        .text(
          `Generated: ${this.formatDateTime(new Date())} IST | Page ${i + 1} of ${pageCount}`,
          50,
          780,
          { align: 'center', width: 500 }
        );

      doc.text(
        'Confidential - For Internal Use Only',
        50,
        792,
        { align: 'center', width: 500 }
      );
    }
  }
}

module.exports = new PDFReportService();
